### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Pllut0** [songoda/EpicSpawners#2]
[19:31:55] [Server thread/WARN]: [EpicSpawners] Task #155 for EpicSpawners v2.2.2 generated an exception
java.lang.NoSuchMethodError: org.bukkit.entity.ArmorStand.setCollidable(Z)V
	at com.songoda.epicspawners.Handlers.b.a(HologramHandler.java:167) ~[?:?]
	at com.songoda.epicspawners.Handlers.b.a(HologramHandler.java:155) ~[?:?]
	at com.songoda.epicspawners.Handlers.b.a(HologramHandler.java:114) ~[?:?]
	at com.songoda.epicspawners.Handlers.b.c(HologramHandler.java:199) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-5f38d38-12698ea]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-5f38d38-12698ea]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**Comment by songoda** [comment]
Resolved with the release of Arconix. I'm really bad at checking these it seems xD
